### ISSUE TITLE
oomcli/apply support yaml syntax

### ISSUE THREAD

**Issue by lianxmfor** [oom-ai/oomstore#728]
subcommand needs support YAML array syntax, like this:

```
items:
    - kind: Feature
      name: state
      group-name: account
      db-value-type: varchar(32)
      description: varchar(32)
    - kind: Feature
      name: credit_score
      group-name: account
      db-value-type: int
      description: int
```
