### ISSUE TITLE
refactor apply for support streaming feature

### ISSUE THREAD

**Issue by lianxmfor** [oom-ai/oomstore#827]
current the file of apply entity is like this:

```yaml
kind: Entity
name: user
length: 8
description: 'description'
batch-features:
- group: device
  description: 'device features'
  features:
  - name: model
    value-type: string
    description: 'model name'
  - name: price
    value-type: int64
    description: 'model price'
```

for support streaming feature well, it will be modified to this:

```yaml
kind: Entity
name: user
length: 8
description: 'description'
groups:
- name: device
  category: batch
  description: 'device features'
  features:
  - name: model
    value-type: string
    description: 'model name'
  - name: price
    value-type: int64
    description: 'model price'
- name: click
  category: stream
  description: 'user click features'
  features:
  - name: user_last_five_click_posts
    value-type: string
    description: 'user last five click posts'
```
