### ISSUE TITLE
rename value-type with type in yaml file

### ISSUE THREAD

**Issue by lianxmfor** [oom-ai/oomstore#828]
this is a yaml file for apply:

```yaml
kind: Entity
name: user
length: 8
description: 'description'
batch-features:
- group: device
  description: 'device features'
  features:
  - name: model
    value-type: string
    description: 'model name'
  - name: price
    value-type: int64
    description: 'model price'
```

The `value-type` is to distinguish the `db-type`, which is no longer available. For simplicity, rename `value-type` to `type`

wait #827 done
